apiVersion: v1
kind: Service
metadata:
  name: mmgriffi-service
spec:
  type: NodePort
  selector:
    myapp: mmgriffi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mmgriffi
  labels:
    myapp: mmgriffi
spec:
  replicas: 3
  selector:
    matchLabels:
      myapp: mmgriffi
  template:
    metadata:
      labels:
        myapp: mmgriffi
    spec:
      containers:
      - name: web
        image: mmgriffi/frozenyogurtshop
        ports:
        - containerPort: 80
