upload-logs-to-elastic:
runs-on: ubuntu-latest
needs: run-demo-app

if: always()
steps:
- name: Upload GitHub Action workflows logs to elastic
  uses: shahargl/upload-github-workflow-logs-to-elastic@1.0.13
  with:
    github_token: "${{ secrets.GITHUB }}"
    github_org: "mmgriffi-org"
    github_repository: "python-demo"
    github_run_id: "${{ github.run_id }}"
    elastic_host: "${{ secrets.ELASTIC_HOST }}"
    elastic_api_key_id: "${{ secrets.ELASTIC_KEY_ID }}"
    elastic_api_key: "${{ secrets.ELASTIC_API_KEY }}"
    elastic_index: "ci-cd"
